import "./globals.css";
import { Navbar } from "@/components/navbar";
import type { Metadata } from "next";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { Container } from "@/components/container";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <Navbar />
          <Container>
            <main>{children}</main>
          </Container>
        </ThemeProvider>
      </body>
    </html>
  );
}
